spring:
  application:
    name: FeedApp
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_OAUTH_CLIENT_ID}
            client-secret: ${GITHUB_OAUTH_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/github
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  cache:
    type: redis
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}

feedapp:
  cache:
    ttl: PT60S
  messaging:
    exchange: feedapp.events
    poll-created:
      queue: feedapp.poll.created.queue
      routing-key: poll.created
    vote-cast:
      queue: feedapp.vote.cast.queue
      routing-key: vote.cast
